### ISSUE TITLE
test auc on Ali CPP dataset

### ISSUE THREAD

**Issue by rockyzhengwu** [xidongbo/AITM#1]
I run the code  on Ali CPP dataset with the default parameters  but the test AUC seem wrong.  @xidongbo  Got any advice aout this ?

![image](https://user-images.githubusercontent.com/10402091/129555304-76850108-5e95-4d3a-b979-5c3e081e6911.png)

**Comment by xidongbo** [comment]
It seems that the AUC on the validation set should be OK, but the AUC on the test set is too low. The AUC of the click task should be 0.6 and that of the purchase task should be 0.65. It seems that the distributions of your test and validation data are inconsistent. You can try to check the test set, the saved model and fine tune the super parameters.

**Comment by rockyzhengwu** [comment]
after reprocess the data test AUC is 0.639 , may be there is some difference in my enviroument , thanks !
![image](https://user-images.githubusercontent.com/10402091/129833267-7fcee6bc-9902-4fb3-b341-430f66d49edf.png)
